package com.cricketscoreprediction.app.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ProgressBar;
import android.widget.RelativeLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import androidx.cardview.widget.CardView;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import com.cricketscoreprediction.app.R;


public final class FragmentScoreBinding implements ViewBinding {
    public final CardView cardF1;
    public final CardView cardF2;
    public final CardView cardFantasy;
    public final CardView cardFi1;
    public final CardView cardFi2;
    public final CardView cardFi3;
    public final CardView cardFi4;
    public final CardView cardPlayer;
    public final CardView cardPrediction;
    public final ImageView img;
    public final ImageView img1;
    public final ImageView imgFlag;
    public final ImageView imgFlagAway;
    public final ImageView imgFlagBowler;
    public final ImageView imgFlagHome;
    public final ImageView imgFlagInning1;
    public final ImageView imgFlagInning2;
    public final ImageView imgFlagInning3;
    public final ImageView imgFlagInning4;
    public final ImageView imgFlagOne;
    public final ImageView imgFlagTwo;
    public final ImageView imgNextPoint;
    public final ImageView imgPlayer;
    public final ImageView imgPlayerBowler;
    public final ImageView imgPlayerImage;
    public final ImageView imgTeam1TopScorer;
    public final ImageView imgTeam1TopTaker;
    public final ImageView imgTeam2TopScorer;
    public final ImageView imgTeam2TopTaker;
    public final LinearLayout llButton;
    public final LinearLayout llHeadToHead;
    public final LinearLayout llMatchSummary;
    public final LinearLayout llPlayerProjection;
    public final LinearLayout llPlayerState;
    public final LinearLayout llPrediction;
    public final LinearLayout llPredictionUc;
    public final LinearLayout llProBowler;
    public final LinearLayout llRecentForm;
    public final LinearLayout llSchedules;
    public final LinearLayout llScoreAway;
    public final LinearLayout llScoreHome;
    public final LinearLayout llStadium;
    public final LinearLayout llTest;
    public final LinearLayout llTopRun;
    public final LinearLayout llTopWicket;
    public final LinearLayout llTwoInnings;
    public final ProgressBar progressFeatureMatch;
    public final RelativeLayout rlFeatureMatch;
    public final RelativeLayout rlNext;
    public final RelativeLayout rlNext1;
    public final RelativeLayout rlNextUc;
    public final RelativeLayout rlSchedules;
    private final ScrollView rootView;
    public final RecyclerView rvAway;
    public final RecyclerView rvHome;
    public final RecyclerView rvPlayerProjection;
    public final RecyclerView rvUpSeries;
    public final ScrollView scrollViewScore;
    public final RecyclerView sliderFeatureMatch;
    public final TextView txt1stBattingAvg;
    public final TextView txt1stBattingWin;
    public final TextView txt4s;
    public final TextView txt6s;
    public final TextView txtAwayTeam;
    public final TextView txtBOver;
    public final TextView txtBWicket;
    public final TextView txtBall;
    public final TextView txtHighestScoreChased;
    public final TextView txtHomeTeam;
    public final TextView txtHthMatches;
    public final TextView txtHthTeam1;
    public final TextView txtHthTeam1Win;
    public final TextView txtHthTeam2;
    public final TextView txtHthTeam2Win;
    public final TextView txtHthTie;
    public final TextView txtLast;
    public final TextView txtName;
    public final TextView txtNameBowler;
    public final TextView txtOverInning1;
    public final TextView txtOverInning2;
    public final TextView txtOverInning3;
    public final TextView txtOverInning4;
    public final TextView txtOverOne;
    public final TextView txtOverTwo;
    public final TextView txtPace;
    public final TextView txtPlayerBol;
    public final TextView txtPlayerName;
    public final TextView txtPlayerRun;
    public final TextView txtProjectedResult;
    public final TextView txtProjection;
    public final TextView txtProjectionOverInning1;
    public final TextView txtProjectionOverInning2;
    public final TextView txtProjectionOverInning3;
    public final TextView txtProjectionOverInning4;
    public final TextView txtProjectionOverOne;
    public final TextView txtProjectionOverTwo;
    public final TextView txtProjectionScoreInning1;
    public final TextView txtProjectionScoreInning2;
    public final TextView txtProjectionScoreInning3;
    public final TextView txtProjectionScoreInning4;
    public final TextView txtProjectionScoreOne;
    public final TextView txtProjectionScoreTwo;
    public final TextView txtScore;
    public final TextView txtScoreInning1;
    public final TextView txtScoreInning2;
    public final TextView txtScoreInning3;
    public final TextView txtScoreInning4;
    public final TextView txtScoreOne;
    public final TextView txtScoreTwo;
    public final TextView txtSpin;
    public final TextView txtStadium;
    public final TextView txtTeam1Scorer;
    public final TextView txtTeam1Taker;
    public final TextView txtTeam1TopScorer;
    public final TextView txtTeam1TopScorerAvg;
    public final TextView txtTeam1TopScorerRun;
    public final TextView txtTeam1TopTaker;
    public final TextView txtTeam1TopTakerAvg;
    public final TextView txtTeam1TopTakerWicket;
    public final TextView txtTeam2Scorer;
    public final TextView txtTeam2Taker;
    public final TextView txtTeam2TopScorer;
    public final TextView txtTeam2TopScorerAvg;
    public final TextView txtTeam2TopScorerRun;
    public final TextView txtTeam2TopTaker;
    public final TextView txtTeam2TopTakerAvg;
    public final TextView txtTeam2TopTakerWicket;
    public final TextView txtTeamAway;
    public final TextView txtTeamAwayBatterRunner;
    public final TextView txtTeamAwayBatterRunnerScore;
    public final TextView txtTeamAwayBatterTop;
    public final TextView txtTeamAwayBatterTopScore;
    public final TextView txtTeamAwayBowlerRunner;
    public final TextView txtTeamAwayBowlerRunnerWicket;
    public final TextView txtTeamAwayBowlerTop;
    public final TextView txtTeamAwayBowlerTopWicket;
    public final TextView txtTeamAwayOver;
    public final TextView txtTeamAwayScore;
    public final TextView txtTeamHome;
    public final TextView txtTeamHomeBatterRunner;
    public final TextView txtTeamHomeBatterRunnerScore;
    public final TextView txtTeamHomeBatterTop;
    public final TextView txtTeamHomeBatterTopScore;
    public final TextView txtTeamHomeBowlerRunner;
    public final TextView txtTeamHomeBowlerRunnerWicket;
    public final TextView txtTeamHomeBowlerTop;
    public final TextView txtTeamHomeBowlerTopWicket;
    public final TextView txtTeamHomeOver;
    public final TextView txtTeamHomeScore;
    public final TextView txtTeamInning1;
    public final TextView txtTeamInning2;
    public final TextView txtTeamInning3;
    public final TextView txtTeamInning4;
    public final TextView txtTeamName;
    public final TextView txtTeamOne;
    public final TextView txtTeamTwo;
    public final TextView txtTitle;
    public final TextView txtWinnerPrediction;

    private FragmentScoreBinding(ScrollView scrollView, CardView cardView, CardView cardView2, CardView cardView3, CardView cardView4, CardView cardView5, CardView cardView6, CardView cardView7, CardView cardView8, CardView cardView9, ImageView imageView, ImageView imageView2, ImageView imageView3, ImageView imageView4, ImageView imageView5, ImageView imageView6, ImageView imageView7, ImageView imageView8, ImageView imageView9, ImageView imageView10, ImageView imageView11, ImageView imageView12, ImageView imageView13, ImageView imageView14, ImageView imageView15, ImageView imageView16, ImageView imageView17, ImageView imageView18, ImageView imageView19, ImageView imageView20, LinearLayout linearLayout, LinearLayout linearLayout2, LinearLayout linearLayout3, LinearLayout linearLayout4, LinearLayout linearLayout5, LinearLayout linearLayout6, LinearLayout linearLayout7, LinearLayout linearLayout8, LinearLayout linearLayout9, LinearLayout linearLayout10, LinearLayout linearLayout11, LinearLayout linearLayout12, LinearLayout linearLayout13, LinearLayout linearLayout14, LinearLayout linearLayout15, LinearLayout linearLayout16, LinearLayout linearLayout17, ProgressBar progressBar, RelativeLayout relativeLayout, RelativeLayout relativeLayout2, RelativeLayout relativeLayout3, RelativeLayout relativeLayout4, RelativeLayout relativeLayout5, RecyclerView recyclerView, RecyclerView recyclerView2, RecyclerView recyclerView3, RecyclerView recyclerView4, ScrollView scrollView2, RecyclerView recyclerView5, TextView textView, TextView textView2, TextView textView3, TextView textView4, TextView textView5, TextView textView6, TextView textView7, TextView textView8, TextView textView9, TextView textView10, TextView textView11, TextView textView12, TextView textView13, TextView textView14, TextView textView15, TextView textView16, TextView textView17, TextView textView18, TextView textView19, TextView textView20, TextView textView21, TextView textView22, TextView textView23, TextView textView24, TextView textView25, TextView textView26, TextView textView27, TextView textView28, TextView textView29, TextView textView30, TextView textView31, TextView textView32, TextView textView33, TextView textView34, TextView textView35, TextView textView36, TextView textView37, TextView textView38, TextView textView39, TextView textView40, TextView textView41, TextView textView42, TextView textView43, TextView textView44, TextView textView45, TextView textView46, TextView textView47, TextView textView48, TextView textView49, TextView textView50, TextView textView51, TextView textView52, TextView textView53, TextView textView54, TextView textView55, TextView textView56, TextView textView57, TextView textView58, TextView textView59, TextView textView60, TextView textView61, TextView textView62, TextView textView63, TextView textView64, TextView textView65, TextView textView66, TextView textView67, TextView textView68, TextView textView69, TextView textView70, TextView textView71, TextView textView72, TextView textView73, TextView textView74, TextView textView75, TextView textView76, TextView textView77, TextView textView78, TextView textView79, TextView textView80, TextView textView81, TextView textView82, TextView textView83, TextView textView84, TextView textView85, TextView textView86, TextView textView87, TextView textView88, TextView textView89, TextView textView90, TextView textView91, TextView textView92, TextView textView93, TextView textView94, TextView textView95, TextView textView96, TextView textView97, TextView textView98, TextView textView99) {
        this.rootView = scrollView;
        this.cardF1 = cardView;
        this.cardF2 = cardView2;
        this.cardFantasy = cardView3;
        this.cardFi1 = cardView4;
        this.cardFi2 = cardView5;
        this.cardFi3 = cardView6;
        this.cardFi4 = cardView7;
        this.cardPlayer = cardView8;
        this.cardPrediction = cardView9;
        this.img = imageView;
        this.img1 = imageView2;
        this.imgFlag = imageView3;
        this.imgFlagAway = imageView4;
        this.imgFlagBowler = imageView5;
        this.imgFlagHome = imageView6;
        this.imgFlagInning1 = imageView7;
        this.imgFlagInning2 = imageView8;
        this.imgFlagInning3 = imageView9;
        this.imgFlagInning4 = imageView10;
        this.imgFlagOne = imageView11;
        this.imgFlagTwo = imageView12;
        this.imgNextPoint = imageView13;
        this.imgPlayer = imageView14;
        this.imgPlayerBowler = imageView15;
        this.imgPlayerImage = imageView16;
        this.imgTeam1TopScorer = imageView17;
        this.imgTeam1TopTaker = imageView18;
        this.imgTeam2TopScorer = imageView19;
        this.imgTeam2TopTaker = imageView20;
        this.llButton = linearLayout;
        this.llHeadToHead = linearLayout2;
        this.llMatchSummary = linearLayout3;
        this.llPlayerProjection = linearLayout4;
        this.llPlayerState = linearLayout5;
        this.llPrediction = linearLayout6;
        this.llPredictionUc = linearLayout7;
        this.llProBowler = linearLayout8;
        this.llRecentForm = linearLayout9;
        this.llSchedules = linearLayout10;
        this.llScoreAway = linearLayout11;
        this.llScoreHome = linearLayout12;
        this.llStadium = linearLayout13;
        this.llTest = linearLayout14;
        this.llTopRun = linearLayout15;
        this.llTopWicket = linearLayout16;
        this.llTwoInnings = linearLayout17;
        this.progressFeatureMatch = progressBar;
        this.rlFeatureMatch = relativeLayout;
        this.rlNext = relativeLayout2;
        this.rlNext1 = relativeLayout3;
        this.rlNextUc = relativeLayout4;
        this.rlSchedules = relativeLayout5;
        this.rvAway = recyclerView;
        this.rvHome = recyclerView2;
        this.rvPlayerProjection = recyclerView3;
        this.rvUpSeries = recyclerView4;
        this.scrollViewScore = scrollView2;
        this.sliderFeatureMatch = recyclerView5;
        this.txt1stBattingAvg = textView;
        this.txt1stBattingWin = textView2;
        this.txt4s = textView3;
        this.txt6s = textView4;
        this.txtAwayTeam = textView5;
        this.txtBOver = textView6;
        this.txtBWicket = textView7;
        this.txtBall = textView8;
        this.txtHighestScoreChased = textView9;
        this.txtHomeTeam = textView10;
        this.txtHthMatches = textView11;
        this.txtHthTeam1 = textView12;
        this.txtHthTeam1Win = textView13;
        this.txtHthTeam2 = textView14;
        this.txtHthTeam2Win = textView15;
        this.txtHthTie = textView16;
        this.txtLast = textView17;
        this.txtName = textView18;
        this.txtNameBowler = textView19;
        this.txtOverInning1 = textView20;
        this.txtOverInning2 = textView21;
        this.txtOverInning3 = textView22;
        this.txtOverInning4 = textView23;
        this.txtOverOne = textView24;
        this.txtOverTwo = textView25;
        this.txtPace = textView26;
        this.txtPlayerBol = textView27;
        this.txtPlayerName = textView28;
        this.txtPlayerRun = textView29;
        this.txtProjectedResult = textView30;
        this.txtProjection = textView31;
        this.txtProjectionOverInning1 = textView32;
        this.txtProjectionOverInning2 = textView33;
        this.txtProjectionOverInning3 = textView34;
        this.txtProjectionOverInning4 = textView35;
        this.txtProjectionOverOne = textView36;
        this.txtProjectionOverTwo = textView37;
        this.txtProjectionScoreInning1 = textView38;
        this.txtProjectionScoreInning2 = textView39;
        this.txtProjectionScoreInning3 = textView40;
        this.txtProjectionScoreInning4 = textView41;
        this.txtProjectionScoreOne = textView42;
        this.txtProjectionScoreTwo = textView43;
        this.txtScore = textView44;
        this.txtScoreInning1 = textView45;
        this.txtScoreInning2 = textView46;
        this.txtScoreInning3 = textView47;
        this.txtScoreInning4 = textView48;
        this.txtScoreOne = textView49;
        this.txtScoreTwo = textView50;
        this.txtSpin = textView51;
        this.txtStadium = textView52;
        this.txtTeam1Scorer = textView53;
        this.txtTeam1Taker = textView54;
        this.txtTeam1TopScorer = textView55;
        this.txtTeam1TopScorerAvg = textView56;
        this.txtTeam1TopScorerRun = textView57;
        this.txtTeam1TopTaker = textView58;
        this.txtTeam1TopTakerAvg = textView59;
        this.txtTeam1TopTakerWicket = textView60;
        this.txtTeam2Scorer = textView61;
        this.txtTeam2Taker = textView62;
        this.txtTeam2TopScorer = textView63;
        this.txtTeam2TopScorerAvg = textView64;
        this.txtTeam2TopScorerRun = textView65;
        this.txtTeam2TopTaker = textView66;
        this.txtTeam2TopTakerAvg = textView67;
        this.txtTeam2TopTakerWicket = textView68;
        this.txtTeamAway = textView69;
        this.txtTeamAwayBatterRunner = textView70;
        this.txtTeamAwayBatterRunnerScore = textView71;
        this.txtTeamAwayBatterTop = textView72;
        this.txtTeamAwayBatterTopScore = textView73;
        this.txtTeamAwayBowlerRunner = textView74;
        this.txtTeamAwayBowlerRunnerWicket = textView75;
        this.txtTeamAwayBowlerTop = textView76;
        this.txtTeamAwayBowlerTopWicket = textView77;
        this.txtTeamAwayOver = textView78;
        this.txtTeamAwayScore = textView79;
        this.txtTeamHome = textView80;
        this.txtTeamHomeBatterRunner = textView81;
        this.txtTeamHomeBatterRunnerScore = textView82;
        this.txtTeamHomeBatterTop = textView83;
        this.txtTeamHomeBatterTopScore = textView84;
        this.txtTeamHomeBowlerRunner = textView85;
        this.txtTeamHomeBowlerRunnerWicket = textView86;
        this.txtTeamHomeBowlerTop = textView87;
        this.txtTeamHomeBowlerTopWicket = textView88;
        this.txtTeamHomeOver = textView89;
        this.txtTeamHomeScore = textView90;
        this.txtTeamInning1 = textView91;
        this.txtTeamInning2 = textView92;
        this.txtTeamInning3 = textView93;
        this.txtTeamInning4 = textView94;
        this.txtTeamName = textView95;
        this.txtTeamOne = textView96;
        this.txtTeamTwo = textView97;
        this.txtTitle = textView98;
        this.txtWinnerPrediction = textView99;
    }

    @Override 
    public ScrollView getRoot() {
        return this.rootView;
    }

    public static FragmentScoreBinding inflate(LayoutInflater layoutInflater) {
        return inflate(layoutInflater, null, false);
    }

    public static FragmentScoreBinding inflate(LayoutInflater layoutInflater, ViewGroup viewGroup, boolean z) {
        View inflate = layoutInflater.inflate(R.layout.fragment_score, viewGroup, false);
        if (z) {
            viewGroup.addView(inflate);
        }
        return bind(inflate);
    }


    public static com.cricketscoreprediction.app.databinding.FragmentScoreBinding bind(View r162) {

        throw new UnsupportedOperationException("Method not decompiled: com.gsbusiness.livecricketscoreprediction.databinding.FragmentScoreBinding.bind(android.view.View):com.gsbusiness.livecricketscoreprediction.databinding.FragmentScoreBinding");
    }
}
